#![cfg_attr(
    not(all(target_os = "macos", target_arch = "aarch64")),
    allow(dead_code)
)]
//! The private wire between the supervisor and its debugger worker. These Rust types are the
//! authority; the worker's Python schemas (`protocol.py`) are generated from them.
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub(crate) const VERSION: &str = "native-observation/17";
pub(crate) const MAX_RECORD: usize = 64 * 1024;
pub(crate) const MAX_TRACE: usize = 4 * 1024 * 1024;
/// Bound of the loaded modifier table file.
pub(crate) const MAX_MODIFIER_TABLE: usize = 32 * 1024 * 1024;

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct WorkerRequest {
    pub version: String,
    pub attempt: String,
    pub game: u32,
    pub executable: String,
    pub target: String,
    /// SHA-256 of each file of the worker package, by file name.
    pub source_hashes: BTreeMap<String, String>,
    pub machine: crate::binding::Machine,
    /// The registries to observe, by internal name.
    pub registries: BTreeMap<String, RegistryBinding>,
    /// A deliberate fault, applied only to its named observation.
    pub fault: Option<crate::protocol::session::Fault>,
    pub fixture: Option<FixtureSetup>,
    /// Read the loaded modifier table at the documentation point, and pause there.
    pub modifiers: Option<ModifierTableBinding>,
    pub deadline_seconds: u64,
}

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct WorkerHello {
    pub version: String,
    pub attempt: String,
    pub game: u32,
    pub worker: u32,
    pub target: String,
    pub source_hashes: BTreeMap<String, String>,
    pub python: String,
    pub lldb: String,
    pub module: String,
}

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct ResumeGrant {
    pub version: String,
    pub attempt: String,
    pub game: u32,
    pub worker: u32,
}

/// Diagnostic producer stages. Strings remain open on the wire so unknown stages lose coverage.
pub(crate) mod diagnostic_stage {
    pub const READER_MALFORMED: &str = "reader-malformed-report";
    pub const READER_UNEXPECTED: &str = "reader-unexpected-report";
    pub const ENGINE_PARSER: &str = "engine-parser-log";
    pub const ENGINE_VALIDATION: &str = "engine-validation-log";

    pub(super) fn python_names() -> serde_json::Value {
        serde_json::json!({
            "reader_malformed": READER_MALFORMED,
            "reader_unexpected": READER_UNEXPECTED,
            "engine_parser": ENGINE_PARSER,
            "engine_validation": ENGINE_VALIDATION,
        })
    }
}

/// Each documented unit variant contributes its serde value and a Python key.
fn python_variants(schema: schemars::Schema) -> serde_json::Map<String, serde_json::Value> {
    let variants = schema
        .get("oneOf")
        .and_then(serde_json::Value::as_array)
        .expect("each wire enum is a documented unit variant");

    variants
        .iter()
        .map(|variant| {
            let wire = variant["const"]
                .as_str()
                .expect("each wire enum has a string wire value");

            (wire.replace('-', "_").to_ascii_lowercase(), wire.into())
        })
        .collect()
}

pub(crate) fn python_bindings() -> String {
    let controls = python_variants(schemars::schema_for!(
        crate::protocol::session::ObservationControl
    ));
    let readers = python_variants(schemars::schema_for!(crate::ReaderKind));
    let hooks = super::hooks::python_names();
    let schemas = serde_json::json!({
        "request": schemars::schema_for!(WorkerRequest),
        "reader_kind": schemars::schema_for!(crate::ReaderKind),
        "hello": schemars::schema_for!(WorkerHello),
        "grant": schemars::schema_for!(ResumeGrant),
        "record": schemars::schema_for!(crate::engine::operations::event_stream::WorkerRecord),
        "pause": schemars::schema_for!(PauseWitness),
        "pause_check": schemars::schema_for!(PauseCheck),
        "modifier_table": schemars::schema_for!(ModifierTable),
    });
    format!(
        "# Generated by Native's private protocol authority. Do not edit.\nimport json\nVERSION = {version:?}\nMAX_RECORD = {MAX_RECORD}\nMAX_TRACE = {MAX_TRACE}\nMAX_MODIFIER_TABLE = {MAX_MODIFIER_TABLE}\nCONTROL = json.loads({controls:?})\nREADER_KIND = json.loads({readers:?})\nHOOK = json.loads({hooks:?})\nDIAGNOSTIC_STAGE = json.loads({stages:?})\nSCHEMAS = json.loads({schemas:?})\n{codec}",
        version = VERSION,
        controls = serde_json::to_string(&controls).unwrap(),
        schemas = serde_json::to_string(&schemas).unwrap(),
        readers = serde_json::to_string(&readers).unwrap(),
        hooks = serde_json::to_string(&hooks).unwrap(),
        stages = serde_json::to_string(&diagnostic_stage::python_names()).unwrap(),
        codec = include_str!("codec.py"),
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn every_reader_kind_uses_its_serde_value_on_both_sides() {
        for value in super::python_variants(schemars::schema_for!(crate::ReaderKind)).values() {
            let kind: crate::ReaderKind = serde_json::from_value(value.clone()).unwrap();
            assert_eq!(serde_json::to_value(kind).unwrap(), *value);
            let event = serde_json::json!({
                "kind": "field-authority", "question": 0, "reader_id": null,
                "reader_kind": value, "reader_family": "Unknown", "storage_supported": false, "unavailable": "unsupported"
            });
            let typed: crate::engine::operations::fixture::FixtureEvent =
                serde_json::from_value(event.clone()).unwrap();
            assert_eq!(serde_json::to_value(typed).unwrap(), event);
        }
    }

    #[test]
    fn every_block_family_round_trips_through_reader_authority() {
        for value in super::python_variants(schemars::schema_for!(crate::BlockFamily)).values() {
            let event = serde_json::json!({
                "kind": "field-authority", "question": 0, "reader_id": null,
                "reader_kind": "Block", "reader_family": value,
                "storage_supported": false, "unavailable": "unsupported"
            });
            let typed: crate::engine::operations::fixture::FixtureEvent =
                serde_json::from_value(event.clone()).unwrap();
            assert_eq!(serde_json::to_value(typed).unwrap(), event);
        }
    }

    #[test]
    fn generated_python_matches_wire_authority() {
        let generated = super::python_bindings();
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("src/binding/platform/macos/observation/protocol.py");
        if std::env::var_os("PDX_NATIVE_GENERATE_PROTOCOL").is_some() {
            std::fs::write(&path, &generated).unwrap();
        }
        assert_eq!(std::fs::read_to_string(path).unwrap(), generated);
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct RegistryBinding {
    pub name: String,
    pub directory: String,
    pub load_entry: u64,
    pub directory_offset: u64,
    pub data_offset: u64,
    pub count_offset: u64,
    pub key_offset: Option<u64>,
    pub key_unavailable: Option<String>,
    pub pointer_size: u64,
    pub string_tag_offset: u64,
}

/// Exact-build entry points and source-location layout for category fixtures.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FixtureBinding {
    pub registration_entry: u64,
    pub load_entry: u64,
    pub field_entry: u64,
    pub reader_lexer_offset: u64,
    pub lexer_file_offset: u64,
    pub file_name_offset: u64,
    pub string_tag_offset: u64,
    pub file_line_offset: u64,
    pub fields: Vec<FixtureFieldBinding>,
    pub outcome_registries: Vec<FixtureOutcomeRegistryBinding>,
    pub validation: Option<FixtureValidationBinding>,
}

/// Formatted logger arguments and the terminal after content validation on one exact build.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FixtureValidationBinding {
    pub log_entry: u64,
    pub log_text_register: String,
    pub unformatted_log_entry: u64,
    pub stream_log_entry: u64,
    pub stream_log_text_register: String,
    pub sourced_log_entry: u64,
    pub sourced_log_text_register: String,
    pub sourced_log_owner_register: String,
    pub sourced_log_source_offset: u64,
    pub complete_entry: u64,
    pub source_file_prefix: String,
    pub source_line_prefix: String,
}

/// A field token selected by the exact-build recipe.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FixtureFieldBinding {
    pub token: u64,
    pub name: String,
}

/// Exact-build hooks and storage layouts for one fixture registry.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FixtureOutcomeRegistryBinding {
    pub registry: String,
    pub load_entry: u64,
    pub reader_entry: u64,
    pub reader_return: u64,
    pub constructor_entry: u64,
    pub member_entry: u64,
    pub malformed_entry: u64,
    pub unexpected_entry: u64,
    pub fields: Vec<FixtureOutcomeFieldBinding>,
}

/// One field's exact token and optional proven string storage.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FixtureOutcomeFieldBinding {
    pub token: u64,
    pub name: String,
    pub storage_offset: Option<u64>,
}

/// One public question resolved against static reader evidence and exact live bindings.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FixtureQuestionSetup {
    pub index: u64,
    pub definition: String,
    pub field: String,
    pub parsing: bool,
    pub diagnostics: bool,
    pub runtime: bool,
    pub reader_id: Option<String>,
    pub reader_kind: crate::ReaderKind,
    pub reader_family: crate::BlockFamily,
    pub token: Option<u64>,
    pub storage_offset: Option<u64>,
    pub storage_unavailable: Option<String>,
}

/// The validated observation selection, resolved before starting the worker.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct FixtureSetup {
    pub file: String,
    pub registration_entries: bool,
    pub field_reads: bool,
    pub validation: bool,
    pub questions: Vec<FixtureQuestionSetup>,
    pub bindings: FixtureBinding,
}

/// Where the engine holds its loaded modifier table and the names of the table's tokens, and the
/// function whose return is the documentation point. Resolved for one exact build.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct ModifierTableBinding {
    pub documentation_entry: u64,
    pub definitions: u64,
    pub array_data_offset: u64,
    pub array_count_offset: u64,
    pub definition_stride: u64,
    pub token_offset: u64,
    pub mask_offset: u64,
    pub lookup: u64,
    pub lookup_size: u64,
    pub lookup_stride: u64,
    pub string_tag_offset: u64,
    /// Registries whose item keys the worker reads at the documentation point, by content
    /// directory.
    pub registries: BTreeMap<String, ModifierRegistryBinding>,
}

/// One registry's database instance and item layout.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct ModifierRegistryBinding {
    /// The global that points to the registry's database.
    pub instance: u64,
    pub directory_offset: u64,
    pub data_offset: u64,
    pub count_offset: u64,
    pub pointer_size: u64,
    pub key_offset: Option<u64>,
    pub key_unavailable: Option<String>,
}

/// What the worker read at the documentation point. It writes this once to
/// `loaded-modifiers.json`; its stream record carries the file's size and SHA-256.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct ModifierTable {
    pub attempt: String,
    /// The table's entries, in table order.
    pub entries: Vec<ModifierEntry>,
    /// The item keys of each bound registry, or why they could not be read.
    pub registries: BTreeMap<String, RegistryKeys>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct ModifierEntry {
    pub name: String,
    pub mask: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "kebab-case")]
pub(crate) enum RegistryKeys {
    Keys(Vec<String>),
    Unavailable(String),
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct PauseWitness {
    pub attempt: String,
    pub game: u32,
    pub worker: u32,
    pub thread: u64,
    pub returned: Vec<String>,
    pub generation: u64,
}

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct PauseCheck {
    pub attempt: String,
    pub game: u32,
    pub generation: u64,
}
