#![cfg_attr(
    not(all(target_os = "macos", target_arch = "aarch64")),
    allow(dead_code)
)]
//! The private wire between the supervisor and its debugger worker. These Rust types are the
//! authority; the worker's Python schemas (`protocol.py`) are generated from them.
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub(crate) const VERSION: &str = "native-observation/5";
pub(crate) const MAX_RECORD: usize = 64 * 1024;
pub(crate) const MAX_TRACE: usize = 4 * 1024 * 1024;

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct WorkerRequest {
    pub version: String,
    pub attempt: String,
    pub game: u32,
    pub executable: String,
    pub target: String,
    /// SHA-256 of each file of the worker package, by file name.
    pub artifacts: BTreeMap<String, String>,
    pub machine: crate::binding::Machine,
    /// The registries to observe, by internal name.
    pub registries: BTreeMap<String, RegistryBinding>,
    /// The registry that receives `control`, when `control` is a fault.
    pub control_registry: Option<String>,
    pub control: String,
    pub deadline_seconds: u64,
}

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct WorkerHello {
    pub version: String,
    pub attempt: String,
    pub game: u32,
    pub worker: u32,
    pub target: String,
    pub artifacts: BTreeMap<String, String>,
    pub python: String,
    pub lldb: String,
    pub module: String,
}

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct ResumeGrant {
    pub version: String,
    pub attempt: String,
    pub game: u32,
    pub worker: u32,
}

pub(crate) fn python_bindings() -> String {
    let schemas = serde_json::json!({
        "request": schemars::schema_for!(WorkerRequest),
        "hello": schemars::schema_for!(WorkerHello),
        "grant": schemars::schema_for!(ResumeGrant),
        "record": schemars::schema_for!(crate::engine::operations::event_stream::WorkerRecord),
        "pause": schemars::schema_for!(PauseWitness),
        "pause_check": schemars::schema_for!(PauseCheck),
    });
    format!(
        "# Generated by Native's private protocol authority. Do not edit.\nimport json\nVERSION = {version:?}\nMAX_RECORD = {MAX_RECORD}\nMAX_TRACE = {MAX_TRACE}\nSCHEMAS = json.loads({schemas:?})\n{codec}",
        version = VERSION,
        schemas = serde_json::to_string(&schemas).unwrap(),
        codec = include_str!("codec.py"),
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn generated_python_matches_wire_authority() {
        let generated = super::python_bindings();
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("src/binding/platform/macos/observation/protocol.py");
        if std::env::var_os("PDX_NATIVE_GENERATE_PROTOCOL").is_some() {
            std::fs::write(&path, &generated).unwrap();
        }
        assert_eq!(std::fs::read_to_string(path).unwrap(), generated);
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct RegistryBinding {
    pub name: String,
    pub directory: String,
    pub load_entry: u64,
    pub directory_offset: u64,
    pub data_offset: u64,
    pub count_offset: u64,
    pub key_offset: u64,
    pub pointer_size: u64,
    pub string_tag_offset: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct PauseWitness {
    pub attempt: String,
    pub game: u32,
    pub worker: u32,
    pub thread: u64,
    pub returned: Vec<String>,
    pub generation: u64,
}

#[derive(Debug, Serialize, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(crate) struct PauseCheck {
    pub attempt: String,
    pub game: u32,
    pub generation: u64,
}
